### ISSUE TITLE
bootstrap.sh gives noise if compiled on OSX

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#2865] opened 2017-05-16 08:40 UTC
It may well be that you only support vitess on Linux but I was trying to build part of the source code on OSX for testing and see that there's no explicit check for the OS used, and right at the beginning I see some noise.

```
[myuser@myhost ~/src/github.com/youtube/vitess]$ ./bootstrap.sh
grep: /proc/cpuinfo: No such file or directory
Updating git submodules...
...
```

I can provide a patch to correctly check the number of CPUs on OSX (but perhaps other parts of the compilation will fail) or simply hide the error with something like this:

```
diff --git a/bootstrap.sh b/bootstrap.sh
index a689e60fd..bb34c0f13 100755
--- a/bootstrap.sh
+++ b/bootstrap.sh
@@ -20,7 +20,7 @@ if [ "$1" = "--skip_root_installs" ]; then
 fi

 # Run parallel make, based on number of cores available.
-NB_CORES=$(grep -c '^processor' /proc/cpuinfo)
+NB_CORES=$(grep -c '^processor' /proc/cpuinfo 2>/dev/null)
 if [ -n "$NB_CORES" ]; then
   export MAKEFLAGS="-j$((NB_CORES+1)) -l${NB_CORES}"
 fi
```

However, it's not clear to me which is "appropriate". I'd guess OSX may not be normally used in production and only Linux is recognised as a valid platform but if so should an explicit check be made in bootstrap.sh to make this clear?  As if I see this and perhaps see other issues I could potentially provide patches as appropriate.

It's not urgent. I'm just curious.

**Comment by acharis** [comment] 2017-05-16 13:00
I'm on Linux, but I think bootstrap is supposed to work on OSX. Something might have gotten by recently. Search bootstrap for Darwin, brew, etc.

**Comment by sougou** [comment] 2017-05-17 16:12
@harshit-gangal or @ashudeep-sharma may be able to give you pointers on this.

**Comment by ashudeep-sharma** [comment] 2017-05-17 16:48
@sjmudd : Did you face any problems while building it on OSX, or was it just some warnings, I had my dev environment on OSX and it used to work fine, we were also running a small test cluster some-times but it was only for development.

**Comment by sjmudd** [comment] 2017-05-26 05:54
The issue was only a warning but it felt wrong.
So provided a patch that's OSX aware now.

**Comment by sougou** [comment] 2017-09-04 18:31
Looks like this can be closed now?

**Comment by michael-berlin** [comment] 2017-09-12 20:25
Yes, I can confirm that this is working :) Closing the issue.

**Closed by michael-berlin** 2017-09-12 20:25 UTC
