### ISSUE TITLE
syntax _binary is not suppored

### ISSUE THREAD

**Issue by xhh1989** [youtube/vitess#3315] opened 2017-10-18 02:58 UTC
insert into t (id, name) values(1, _binary'Jim Gray'); _binary is not suppored, with out the underline is ok, like :  insert into t (id, name) values(1,  binary'Jim Gray');

**Comment by acharis** [comment] 2017-10-18 22:15
duplicate of https://github.com/youtube/vitess/issues/2890

**Closed** 2017-10-19 02:13 UTC
