### ISSUE TITLE
Handle auto commit changes in VTGate

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#3041] opened 2017-08-05 20:24 UTC
If there is an ongoing transaction and VTGate receives auto-commit value as true.
In the form of 
1. Session variable value of auto-commit set to true
2. SET autocommit = 1
3. SET autocommit = true

VTGate should 
1. Try to commit the ongoing transaction with its commit policy (best-effort / 2PC).
2. Set the session variable value of auto-commit to true and send back to the client.

**Comment by sougou** [comment] 2017-08-15 17:32
Updating this issue with the recent discussion on Slack.

This is my understanding of MySQL autocommit behavior for all statements including selects:
* ON: every statement is a self-contained transaction.
* ON, and a `begin` is issued: a transaction is started that will remain open until the next `commit` or `rollback`.
* OFF: an implicit transaction is started on the first statement received and the transaction will remain open until the next `commit` or `rollback`.
* OFF->ON: If there is an existing transaction, it is immediately committed.
* ON->OFF: no immediate action is taken. But future behavior will be changed as described above.

It is important to note that autocommit=OFF is not a desirable option for reading from replicas. This is because you will obtain an unchanging snapshot of the database at the beginning and will see no future changes. For this reason, people always connect to replicas with autocommit=ON, and rely on the replica's read-only behavior to protect from accidental attempts to write to it.

For the master, all of the above combinations seem to be in use.

There are a few differences between Vitess and MySQL:

MySQL | Vitess
---------- | --------
You make explicit connections to the master or replica. You cannot 'change' a connection from master to replica | You are connected to the entire fleet. You can change a connection from master to replica through the `USE` statement. This can also be done by the client by changing `target_string` in the protobuf message.
You can start a replica transaction with `begin` and perform only reads, which will give you an unchanging snapshot until the next `commit` or `rollback` | This is not supported in Vitess

Here is how we can reconcile the above differences:
* If the target type of a request is determined to be the master, then we behave just like MySQL. This can be achieved by using the `in_transaction` to track transaction state.
* If the target type is a replica:
  * The value of `autocommit` is ignored.
  * DMLs and `begin` are rejected.
  * If `in_transaction` is true, the request is rejected.
* If a `USE` statement is issued, a `master` to `replica` transition is allowed only if you are not in a transaction.

The above behavior is mostly backward compatible. The main difference is that we now start an implicit transaction in some cases, where the previous behavior was to return an error. If this is acceptable, I'll go ahead with the implementation.

**Comment by harshit-gangal** [comment] 2017-08-16 10:14
Almost everything looks good.
Few concern/cases

- If target type is replica, why to reject for in_transaction being true, can this be ignored?
- If VTGates receive SET Query how will it impact the session. It will be good to document that as well.
   Specifically keyspace, shard, tablet_type, auto_commit.
- If VTGate receives begin/commit/rollback how it will impact Query.Session?

**Comment by sougou** [comment] 2017-08-19 03:41
Recapping discussion on Slack and subsequent research:

Starting an implicit transaction if autocommit is OFF will break backward compatibility. This is because the legacy clients don't specify that flag, and the default value for autocommit is OFF. The legacy behavior in such cases was to allow transaction-less reads. This needs to be preserved because existing users depend on this.

We also want to eventually match MySQL's behavior. The transition plan is as follows:
* VTGate will not start an implicit transaction for the 3.0 release.
* All clients will be changed to turn on autocommit by default. With this setting, transaction-less reads will work as before.
* For 3.1, we enable starting of implicit transactions at the VTGate level. 3.0 clients will be unaffected because of the default autocommit setting.

As for other behavior:
* I just confirmed that a new `begin` will cause any current transaction to be committed, and a new transaction will be started. VTGate already mimics this behavior.
* Ignoring `in_transaction` for replica is not a good idea because it may give the application the false impression that we support snapshot reads. So, it's better to explicitly fail and disallow transactions when the app is using a replica. To support this behavior, the following transitions will not be allowed:
  * `use @<non-master>` if `in_transaction` is ON.
  * `begin` if target string is not master.
  * Any request with `in_transaction` ON and target string is non-master.
* Turning autocommit ON will cause any existing transactions to be committed. I will make this change.

Although not very material, we could also require autocommit to be ON for replica reads. If so, we can code this behavior for 3.1.

**Comment by harshit-gangal** [comment] 2017-08-19 12:34
+1

**Comment by harshit-gangal** [comment] 2017-08-20 12:03
I checked tx_conn code. As per this my understanding is,
in_transaction flag should not be changed by clients.
It should be set only once with auto_commit true and in_transaction false.
Rest any change of auto_commit or begin / commit / rollback, VTGate will make changes to this flag appropriately.

**Comment by sougou** [comment] 2017-08-21 03:32
Basically, the only part that is not mysql-compatible right now is the implicit transaction if autocommit is OFF. So, that's the only additional work that JDBC has to do: if autocommit is false, and in_transaction is also false, just begin a transaction. You can do this by either calling "begin", or just setting the in_transaction flag to true.

**Closed** 2017-12-05 07:35 UTC
Labels: P2, Type: Feature Request
