### ISSUE TITLE
examples/demo doesn't work with the v2.0.0 release tag (at least on OSX)

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#2064] opened 2016-09-16 23:06 UTC
Hi, I have problem running the examples/demo example from the v2.0.0 tag.

Steps to reproduce:

1) git clone vitess
2) git checkout v2.0.0 (or release-2.0.0)
3) cd examples/demo
4) ./run.py

I'm getting this output:

```
~/DEV/vitess/src/github.com/youtube/vitess/examples/demo • ./run.py
I0917 00:50:36.824296   10237 dbconfigs.go:211] DBConfigs: {
  "App": {
    "engine": "",
    "host": "",
    "port": 0,
    "uname": "",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/mysql.sock",
    "charset": "",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": "",
    "Keyspace": "",
    "Shard": ""
  },
  "Dba": {
    "engine": "",
    "host": "",
    "port": 0,
    "uname": "vt_dba",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/mysql.sock",
    "charset": "utf8",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": ""
  },
  "Filtered": {
    "engine": "",
    "host": "",
    "port": 0,
    "uname": "",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/mysql.sock",
    "charset": "",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": ""
  },
  "Repl": {
    "engine": "",
    "host": "",
    "port": 0,
    "uname": "",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/mysql.sock",
    "charset": "",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": ""
  }
}
I0917 00:50:36.824988   10237 mysqld.go:408] mysqlctl.Init
I0917 00:50:36.825006   10237 mysqld.go:525] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001
I0917 00:50:36.825203   10237 mysqld.go:558] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/data
I0917 00:50:36.825305   10237 mysqld.go:558] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/innodb
I0917 00:50:36.825391   10237 mysqld.go:558] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/relay-logs
I0917 00:50:36.825467   10237 mysqld.go:558] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/bin-logs
I0917 00:50:36.825582   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/data
I0917 00:50:36.825592   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/innodb/data
I0917 00:50:36.825665   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/innodb/logs
I0917 00:50:36.825828   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/tmp
I0917 00:50:36.825926   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/relay-logs
I0917 00:50:36.825940   10237 mysqld.go:535] creating directory /Users/rasta/DEV/vitess/vtdataroot/vttest_NbX7q/vt_0000000001/bin-logs
I0917 00:50:36.825984   10237 mysqld.go:499] make_mycnf hook doesn't exist, reading default template files
I0917 00:50:36.828240   10237 mysqld.go:387] execCmd: /usr/local/opt/mysql56/sbin/mysqld  [--version]
I0917 00:50:36.833921   10237 mysqld.go:400] execCmd: command returned: 
E0917 00:50:36.834225   10237 mysqlctl.go:213] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld: 
Traceback (most recent call last):
  File "/Users/rasta/DEV/vitess/src/github.com/youtube/vitess/py/vttest/run_local_database.py", line 135, in <module>
    main(options)
  File "/Users/rasta/DEV/vitess/src/github.com/youtube/vitess/py/vttest/run_local_database.py", line 57, in main
    web_dir=cmdline_options.web_dir) as local_db:
  File "/Users/rasta/DEV/vitess/py-vtdb/vttest/local_database.py", line 429, in __enter__
    self.setup()
  File "/Users/rasta/DEV/vitess/py-vtdb/vttest/local_database.py", line 50, in setup
    self.mysql_db.setup()
  File "/Users/rasta/DEV/vitess/py-vtdb/vttest/mysql_db_mysqlctl.py", line 41, in setup
    raise Exception('mysqlctl failed', result)
Exception: ('mysqlctl failed', 1)
Traceback (most recent call last):
  File "./run.py", line 80, in <module>
    main()
  File "./run.py", line 68, in main
    sp = start_vitess()
  File "./run.py", line 54, in start_vitess
    json.loads(sp.stdout.readline())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I don't know if this also happens in Linux, I tested only OSX.

Btw current master branch works for me.

**Comment by enisoc** [comment] 2016-09-28 10:41
When you go back from `master` to the `v2.0.0` tag, do you clear out the `$VTROOT/dist` folder and re-run `boostrap.sh` and `make build`? Just checking since it's not clear from your reproduction steps if you do this, and we don't expect the old demo scripts to still work with the latest binaries.

**Comment by Rastusik** [comment] 2016-09-28 10:58
Yes, sorry, I forgot to mention that. I did everything from scratch to be sure.

**Comment by Rastusik** [comment] 2016-10-04 20:36
I just figured out the problem (got busy with something different for a while) ... in the 2.0.0 version the  problem was that when running demo/run.py , a python script (don't know which one, can look if needed) was running this command: VT_MYSQL_ROOT/**sbin**/mysql --version ... **sbin** is not a standard directory I suppose, I onlhy have a **bin** directory, so I had to create a symlink, which helped ... 

Shall I close this issue? I think it is already fixed in the current master branch. I have no idea how I could have missed this before

**Comment by michael-berlin** [comment] 2016-10-04 20:45
If it's an easy fix, let's cherry pick it in the 2.0.0 branch (unless @enisoc disagrees).

I'll try to find the fix in the commits. If you know which one, let me know.

**Comment by Rastusik** [comment] 2016-10-04 21:09
I haven't looked for it, don't have time for that right now. I think this worked on linux (tested it earlier today) so this seems to be OSX specific. I'm not sure if this is so important to fix, but maybe it would help some of the few OSX users later.

**Comment by michael-berlin** [comment] 2016-10-04 22:10
In that case let's close the issue and not backport the fix.

OSX users can use the master branch if they want to run the demo ;-)

**Closed by michael-berlin** 2016-10-04 22:10 UTC
