### ISSUE TITLE
vitess/examples/local$ ./lvtctl.sh help error

### ISSUE THREAD

**Issue by elipoke** [youtube/vitess#2845] opened 2017-05-11 06:29 UTC
root@vitess:/opt/vitess/vitess/bin# ./vtctlclient -server localhost:15999 help
2017/05/11 14:28:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:15999: getsockopt: connection refused"; Reconnecting to {localhost:15999 <nil>}
2017/05/11 14:28:18 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:15999: getsockopt: connection refused"; Reconnecting to {localhost:15999 <nil>}

**Comment by michael-berlin** [comment] 2017-05-11 17:10
> connection refused

The problem is that vtctld is not running.

It's probably not running because it immediately shut down again when you ran it as user "root": https://groups.google.com/d/msg/vitess/OroN9q8GIy4/Tm8Vxv4BAwAJ

From the Vitess side, this is working as intended. Therefore, I'm closing this issue.

**Closed by michael-berlin** 2017-05-11 17:10 UTC

**Comment by elipoke** [comment] 2017-05-12 01:02
when I use user 'vitess' tctld is running

vitess/examples/local$ ./vttablet-up.sh

fail:

E0512 08:58:33.698617    6955 mysqld.go:551] mysqld --initialize-insecure failed: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000101/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.698847    6955 mysqlctl.go:243] failed init mysql: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000101/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699010    6958 mysqld.go:551] mysqld --initialize-insecure failed: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000104/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699147    6957 mysqld.go:551] mysqld --initialize-insecure failed: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000103/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699222    6954 mysqld.go:551] mysqld --initialize-insecure failed: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000100/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699251    6958 mysqlctl.go:243] failed init mysql: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000104/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699443    6957 mysqlctl.go:243] failed init mysql: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000103/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699520    6954 mysqlctl.go:243] failed init mysql: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000100/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.699830    6956 mysqld.go:551] mysqld --initialize-insecure failed: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000102/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
E0512 08:58:33.700050    6956 mysqlctl.go:243] failed init mysql: /usr/sbin/mysqld: exit status 1, output: mysqld: [ERROR] Could not open required defaults file: /opt/vitess/vitess/vtdataroot/vt_0000000102/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
Starting vttablet for test-0000000100...
Access tablet test-0000000100 at http://vitess:15100/debug/status
Starting vttablet for test-0000000101...
Access tablet test-0000000101 at http://vitess:15101/debug/status
Starting vttablet for test-0000000102...
Access tablet test-0000000102 at http://vitess:15102/debug/status
Starting vttablet for test-0000000103...
Access tablet test-0000000103 at http://vitess:15103/debug/status
Starting vttablet for test-0000000104...
Access tablet test-0000000104 at http://vitess:15104/debug/status

**Comment by sougou** [comment] 2017-05-13 16:39
It looks like your VTDATAROOT is set to /opt/vitess/vitess/vtdataroot. Do
you have access to that directory?
Or, you could try setting it to point to a different location.

We usually set to to be the same as $VTROOT/vtdataroot.
