### ISSUE TITLE
Unable to build vitess with MariaDB 10.1

### ISSUE THREAD

**Issue by byzhangyong** [youtube/vitess#1437] opened 2016-01-13 02:39 UTC
Hi,

I'm trying to build Vitess on Ubuntu 14.04.3 with Maria DB (have tried 10.1.19 and also 10.0.22).

Somehow even after I removed the 10.1.19 (and also the older version) version, I'm getting this:

$ mysql_config --version

10.1.9

But the real problem is here:

```
vitess$ make build

Mon Dec 7 17:30:19 CET 2015: Building source tree

# github.com/youtube/vitess/go/mysql

/tmp/go-build704689855/github.com/youtube/vitess/go/mysql/_obj/vtmysql.o: In function `vt_cli_safe_read':

go/mysql/vtmysql.c:160: undefined reference to `cli_safe_read'

/tmp/go-build704689855/github.com/youtube/vitess/go/mysql/_obj/vtmysql.o: In function `vt_shutdown':

go/mysql/vtmysql.c:169: undefined reference to `vio_socket_shutdown'

collect2: error: ld returned 1 exit status

godep: go exit status 2

make: *** [build] Error 1
```

I was following the steps from this link: http://vitess.io/getting-started/local-instance.html#manual-build

Does anybody have a clue what might be wrong?

Thank you

**Comment by michael-berlin** [comment] 2016-01-13 06:32
Hi,

Do you have the package ```libmariadbclient-dev``` installed?

If so and it doesn't work, I guess our link options use the wrong filename:

We link the MariaDB client library statically, see:

https://github.com/youtube/vitess/blob/master/bootstrap.sh#L163

```sh
if [ "$MYSQL_FLAVOR" == "MariaDB" ]; then
  # Use static linking because the shared library doesn't export
  # some internal functions we use, like cli_safe_read.
  echo "Libs:" "$($VT_MYSQL_ROOT/bin/mysql_config --libs_r | sed 's,-lmysqlclient_r,-l:libmysqlclient.a -lstdc++,')" >> $VTROOT/lib/gomysql.pc
```

As you can see, we link in "libmysqlclient.a". However, ```libmariadbclient-dev``` provides only a ```libmariadbclient.a``` file. See: http://packages.ubuntu.com/trusty/amd64/libmariadbclient-dev/filelist

Please try this:

- in bootstrap.sh, replace ```-l:libmysqlclient.a``` with ```-l:libmariadbclient.a```
- run bootstrap.sh again. Does make build work after that?

**Comment by byzhangyong** [comment] 2016-01-13 07:59
build  failure

user@client:~$ sudo find / -name "libmariadbclient.a"
/usr/lib/x86_64-linux-gnu/libmariadbclient.a

--------------------------------------------------------------------------------------------------------
user@client:~/make/vitess/src/github.com/youtube/vitess$ make build 
2016年 01月 13日 星期三 15:52:59 CST: Building source tree
# github.com/youtube/vitess/go/mysql
/tmp/go-build498598860/github.com/youtube/vitess/go/mysql/_obj/vtmysql.o：在函数‘vt_cli_safe_read’中：
go/mysql/vtmysql.c:160：对‘cli_safe_read’未定义的引用
/tmp/go-build498598860/github.com/youtube/vitess/go/mysql/_obj/vtmysql.o：在函数‘vt_shutdown’中：
go/mysql/vtmysql.c:169：对‘vio_socket_shutdown’未定义的引用
collect2: error: ld returned 1 exit status
godep: go exit status 2
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1
------------------------------------------------------------------------------------------------------------------------
bootstrap.sh

if [ "$MYSQL_FLAVOR" == "MariaDB" ]; then
  # Use static linking because the shared library doesn't export
  # some internal functions we use, like cli_safe_read.
  echo "Libs:" "$($VT_MYSQL_ROOT/bin/mysql_config --libs_r | sed 's,-lmysqlclient_r,-l:libmariadbclient.a -lstdc++,')" >> $VTROOT/lib/gomysql.pc

--------------------------------------------------------------------------------------------------------------
.bashrc 

#mraidb
#export MYSQL_FLAVOR=MariaDB
export VT_MYSQL_ROOT=/usr/local/mysql
export PATH=$PATH:/usr/local/mysql/bin
---------------------------------------------------------------------

**Comment by enisoc** [comment] 2016-01-13 22:41
It could be that our build doesn't work yet with 10.1, as we haven't tested with it.

It should work if you can get `mysql_config --version` to return `10.0.22` by installing the right version of `libmariadbclient-dev`.

**Comment by michael-berlin** [comment] 2016-01-14 05:27
First of all, please ignore my previous comments. I was assuming you would use the stock packages from Ubuntu. But I just found out that these are way too old (5.5).

I reproduced your issue with MariaDB 10.1.

The problem is that our work-around for MariaDB no longer works:

As I stated earlier, we link libmariadbclient statically because some functions are not exported e.g. "cli_safe_read". However, for 10.1 the build tries to link dynamically against the lib and complains that it doesn't find the not-exported functions:

```
go/mysql/vtmysql.c:160: undefined reference to `cli_safe_read'
```

The solution is easy. We must adjust our MariaDB work-around in boostrap.sh:

https://github.com/youtube/vitess/blob/master/bootstrap.sh#L163

```sh
if [ "$MYSQL_FLAVOR" == "MariaDB" ]; then
  # Use static linking because the shared library doesn't export
  # some internal functions we use, like cli_safe_read.
  echo "Libs:" "$($VT_MYSQL_ROOT/bin/mysql_config --libs_r | sed 's,-lmysqlclient_r,-l:libmysqlclient.a -lstdc++,')" >> $VTROOT/lib/gomysql.pc
```

It looks like with 10.1 MariaDB ```libmysqlclient``` is reentrant by default and they got rid of the special library ```libmysqlclient_r```. Therefore, ```mysql_config --libs_r``` now returns ```libmysqlclient``` instead of ```libmysqlclient_r```.

I've created https://github.com/youtube/vitess/pull/1444 to fix the issue.

**Comment by byzhangyong** [comment] 2016-01-14 08:27
Successfully resolved the problem, thank you，，thank you

**Comment by michael-berlin** [comment] 2016-01-14 21:49
Fixed in https://github.com/youtube/vitess/pull/1444

**Closed by michael-berlin** 2016-01-14 21:49 UTC
