### ISSUE TITLE
OSX: unable to build

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#1878] opened 2016-07-18 12:38 UTC
Hi,

I'm not sure if I've broken my OSX setup or not, but I'm getting these error messages when trying to build vitess since today morning:

```bash
Mon Jul 18 14:33:47 CEST 2016: Building source tree
import cycle not allowed
package github.com/youtube/vitess/go/cmd/automation_client
	imports github.com/youtube/vitess/go/vt/proto/automationservice
	imports .
	imports .
go/vt/proto/automationservice/automationservice.pb.go:15:8: cannot find package "_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/github.com/golang/protobuf/proto" in any of:
/usr/local/Cellar/go/1.6/libexec/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/github.com/golang/protobuf/proto (from $GOROOT)
	/Users/mfris/DEV/vitess_build/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/github.com/golang/protobuf/proto (from $GOPATH)
go/vt/proto/automationservice/automationservice.pb.go:21:2: cannot find package "_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/golang.org/x/net/context" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/golang.org/x/net/context (from $GOROOT)
	/Users/mfris/DEV/vitess_build/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/golang.org/x/net/context (from $GOPATH)
go/vt/proto/automationservice/automationservice.pb.go:22:2: cannot find package "_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/google.golang.org/grpc" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/google.golang.org/grpc (from $GOROOT)
	/Users/mfris/DEV/vitess_build/src/_/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/vendor/google.golang.org/grpc (from $GOPATH)
/Users/mfris/DEV/vitess_build/src/github.com/youtube/vitess/go/vt/proto/automationservice/automationservice.pb.go:18:8: local import "." in non-local package
import cycle not allowed
...
```

Any ideas what I might have done wrong?

Thanks

**Comment by Rastusik** [comment] 2016-07-18 12:42
I think it started after this commit https://github.com/youtube/vitess/commit/cded5ebd130438fbdeb9f94c8971c23359b88d43

Not 100% sure though.

**Comment by ashudeep-sharma** [comment] 2016-07-18 16:12
I did a fresh setup, the bootstrap runs fine, but make build gives this error
Mon Jul 18 21:39:09 IST 2016: Compiling proto definitions
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
make: *** [install_protoc-gen-go] Error 64

On removing the u option from the MakeFile i am able to reproduce this.

**Comment by Rastusik** [comment] 2016-07-18 18:09
@ashudeep-sharma yes, that's #1877

**Comment by enisoc** [comment] 2016-07-18 20:19
The commit you identified is where we added `make proto` as a dependency for `make build`. Before that, you probably had never run `make proto` on OS X, since the files it generates are checked into source control.

Can you check if `make proto && make build` hits the same error for you, at the commit where you found `make build` still works?

**Comment by Rastusik** [comment] 2016-07-18 20:31
with the -u flag in cp

```bash
~/DEV/vitess/src/github.com/youtube/vitess • make proto && make build
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
make: *** [install_protoc-gen-go] Error 64
```

after I apply the sed fix from https://github.com/youtube/vitess/commit/88d381596d08df6da46eab6ffa93fe178b1bb807

I'm getting the same error.

**Comment by enisoc** [comment] 2016-07-18 21:35
That seems to confirm that `make proto` just doesn't work on OS X (and likely never did).

I don't have an OS X machine anymore to try this on. Could you share what the diffs look like after `make proto` runs?

**Comment by Rastusik** [comment] 2016-07-18 21:38
```
diff --git a/Makefile b/Makefile
index 7af2514..b50980a 100644
--- a/Makefile
+++ b/Makefile
@@ -91,7 +91,7 @@ php_test:
 # install vendor'd programs: https://github.com/kardianos/govendor/issues/117
 install_protoc-gen-go:
 	mkdir -p $${GOPATH}/src/github.com/golang/
-	cp -au vendor/github.com/golang/protobuf $${GOPATH}/src/github.com/golang/
+	cp -a vendor/github.com/golang/protobuf $${GOPATH}/src/github.com/golang/
 	go install github.com/golang/protobuf/protoc-gen-go
 
 # This rule rebuilds all the go files from the proto definitions for gRPC.
@@ -101,7 +101,7 @@ install_protoc-gen-go:
 # 4. (python) run protoc for each proto and put in py/vtproto/
 proto: install_protoc-gen-go
 	find proto -maxdepth 1 -name '*.proto' -print | sed 's/^proto\///' | sed 's/\.proto//' | xargs -I{} $$VTROOT/dist/grpc/usr/local/bin/protoc -Iproto proto/{}.proto --go_out=plugins=grpc:go/vt/proto/{}
-	find go/vt/proto -name "*.pb.go" | xargs sed --in-place -r -e 's,import ([a-z0-9_]+) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'
+	find go/vt/proto -name "*.pb.go" | xargs sed -i -e 's,import \([a-z0-9_]\+\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'
 	find proto -maxdepth 1 -name '*.proto' -print | sed 's/^proto\///' | sed 's/\.proto//' | xargs -I{} $$VTROOT/dist/grpc/usr/local/bin/protoc -Iproto proto/{}.proto --python_out=py/vtproto --grpc_out=py/vtproto --plugin=protoc-gen-grpc=$$VTROOT/dist/grpc/usr/local/bin/grpc_python_plugin
 
 # Generate the PHP proto files in a Docker container, and copy them back.
diff --git a/go/vt/proto/automationservice/automationservice.pb.go b/go/vt/proto/automationservice/automationservice.pb.go
index e457c28..0f829c5 100644
--- a/go/vt/proto/automationservice/automationservice.pb.go
+++ b/go/vt/proto/automationservice/automationservice.pb.go
@@ -15,7 +15,7 @@ package automationservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import automation "github.com/youtube/vitess/go/vt/proto/automation"
+import automation "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/binlogdata/binlogdata.pb.go b/go/vt/proto/binlogdata/binlogdata.pb.go
index e13abde..a84f893 100644
--- a/go/vt/proto/binlogdata/binlogdata.pb.go
+++ b/go/vt/proto/binlogdata/binlogdata.pb.go
@@ -24,8 +24,8 @@ package binlogdata
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import query "github.com/youtube/vitess/go/vt/proto/query"
-import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
+import query "."
+import topodata "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/binlogservice/binlogservice.pb.go b/go/vt/proto/binlogservice/binlogservice.pb.go
index 02d7893..d3ce817 100644
--- a/go/vt/proto/binlogservice/binlogservice.pb.go
+++ b/go/vt/proto/binlogservice/binlogservice.pb.go
@@ -15,7 +15,7 @@ package binlogservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import binlogdata "github.com/youtube/vitess/go/vt/proto/binlogdata"
+import binlogdata "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/query/query.pb.go b/go/vt/proto/query/query.pb.go
index 84340b5..f92212b 100644
--- a/go/vt/proto/query/query.pb.go
+++ b/go/vt/proto/query/query.pb.go
@@ -45,8 +45,8 @@ package query
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
-import vtrpc "github.com/youtube/vitess/go/vt/proto/vtrpc"
+import topodata "."
+import vtrpc "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/queryservice/queryservice.pb.go b/go/vt/proto/queryservice/queryservice.pb.go
index e90400d..50b9549 100644
--- a/go/vt/proto/queryservice/queryservice.pb.go
+++ b/go/vt/proto/queryservice/queryservice.pb.go
@@ -15,7 +15,7 @@ package queryservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import query "github.com/youtube/vitess/go/vt/proto/query"
+import query "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go b/go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
index 9d3277a..8591cf0 100644
--- a/go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
+++ b/go/vt/proto/tabletmanagerdata/tabletmanagerdata.pb.go
@@ -102,10 +102,10 @@ package tabletmanagerdata
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import query "github.com/youtube/vitess/go/vt/proto/query"
-import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
-import replicationdata "github.com/youtube/vitess/go/vt/proto/replicationdata"
-import logutil "github.com/youtube/vitess/go/vt/proto/logutil"
+import query "."
+import topodata "."
+import replicationdata "."
+import logutil "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go b/go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
index 4eee827..d60998a 100644
--- a/go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
+++ b/go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go
@@ -15,7 +15,7 @@ package tabletmanagerservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import tabletmanagerdata "github.com/youtube/vitess/go/vt/proto/tabletmanagerdata"
+import tabletmanagerdata "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/throttlerservice/throttlerservice.pb.go b/go/vt/proto/throttlerservice/throttlerservice.pb.go
index 778a8b1..4d61516 100644
--- a/go/vt/proto/throttlerservice/throttlerservice.pb.go
+++ b/go/vt/proto/throttlerservice/throttlerservice.pb.go
@@ -15,7 +15,7 @@ package throttlerservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import throttlerdata "github.com/youtube/vitess/go/vt/proto/throttlerdata"
+import throttlerdata "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/vtctldata/vtctldata.pb.go b/go/vt/proto/vtctldata/vtctldata.pb.go
index 375df6b..2d67db9 100644
--- a/go/vt/proto/vtctldata/vtctldata.pb.go
+++ b/go/vt/proto/vtctldata/vtctldata.pb.go
@@ -17,7 +17,7 @@ package vtctldata
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import logutil "github.com/youtube/vitess/go/vt/proto/logutil"
+import logutil "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/vtctlservice/vtctlservice.pb.go b/go/vt/proto/vtctlservice/vtctlservice.pb.go
index 7034332..7c004a2 100644
--- a/go/vt/proto/vtctlservice/vtctlservice.pb.go
+++ b/go/vt/proto/vtctlservice/vtctlservice.pb.go
@@ -15,7 +15,7 @@ package vtctlservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import vtctldata "github.com/youtube/vitess/go/vt/proto/vtctldata"
+import vtctldata "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/vtgate/vtgate.pb.go b/go/vt/proto/vtgate/vtgate.pb.go
index 5c16cab..f9d354a 100644
--- a/go/vt/proto/vtgate/vtgate.pb.go
+++ b/go/vt/proto/vtgate/vtgate.pb.go
@@ -50,9 +50,9 @@ package vtgate
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import query "github.com/youtube/vitess/go/vt/proto/query"
-import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
-import vtrpc "github.com/youtube/vitess/go/vt/proto/vtrpc"
+import query "."
+import topodata "."
+import vtrpc "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/vtgateservice/vtgateservice.pb.go b/go/vt/proto/vtgateservice/vtgateservice.pb.go
index f9f4734..7b6ad68 100644
--- a/go/vt/proto/vtgateservice/vtgateservice.pb.go
+++ b/go/vt/proto/vtgateservice/vtgateservice.pb.go
@@ -15,7 +15,7 @@ package vtgateservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import vtgate "github.com/youtube/vitess/go/vt/proto/vtgate"
+import vtgate "."
 
 import (
 	context "golang.org/x/net/context"
diff --git a/go/vt/proto/vtworkerdata/vtworkerdata.pb.go b/go/vt/proto/vtworkerdata/vtworkerdata.pb.go
index c9c403d..3e92149 100644
--- a/go/vt/proto/vtworkerdata/vtworkerdata.pb.go
+++ b/go/vt/proto/vtworkerdata/vtworkerdata.pb.go
@@ -17,7 +17,7 @@ package vtworkerdata
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import logutil "github.com/youtube/vitess/go/vt/proto/logutil"
+import logutil "."
 
 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
diff --git a/go/vt/proto/vtworkerservice/vtworkerservice.pb.go b/go/vt/proto/vtworkerservice/vtworkerservice.pb.go
index bd390a0..ebe7a96 100644
--- a/go/vt/proto/vtworkerservice/vtworkerservice.pb.go
+++ b/go/vt/proto/vtworkerservice/vtworkerservice.pb.go
@@ -15,7 +15,7 @@ package vtworkerservice
 import proto "github.com/golang/protobuf/proto"
 import fmt "fmt"
 import math "math"
-import vtworkerdata "github.com/youtube/vitess/go/vt/proto/vtworkerdata"
+import vtworkerdata "."
 
 import (
 	context "golang.org/x/net/context"

```

**Comment by enisoc** [comment] 2016-07-18 21:45
Ah! So it's just the sed command that I tried to fix for OS X. It's still not matching anything in OS X (or not doing an in-place update, or not giving the right list of files), although it works in Linux.

Could someone with OS X try to figure out why this command isn't working?

https://github.com/youtube/vitess/blob/master/Makefile#L136

**Comment by pivanof** [comment] 2016-07-18 21:49
Maybe it's because the -r flag is omitted? Does it work without -r flag on Linux? Though the similar flag on OS X seem to be -E (see https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/sed.1.html).

**Comment by Rastusik** [comment] 2016-07-18 22:00
this seems to do the job:

```
sed -E -i -e 's,import ([a-z0-9_]+) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'
```

**Comment by enisoc** [comment] 2016-07-18 22:06
I was hoping to avoid `-E` because it's not supported in Linux (well it is, but it's called `-r`). I'd rather not have to add platform conditionals to the command if possible. Is there a way to make it work in non-extended mode?

**Comment by pivanof** [comment] 2016-07-18 22:17
I was able to make it work using the following:

sed -i -e 's,import \([a-z0-9_]\+\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'

@Rastusik can you verify if that works on OS X?

**Comment by pivanof** [comment] 2016-07-18 22:19
Hm... Github helpfully removed all the backslashes. They should be before parenthesis and plus sign:

sed -i -e 's,import \\([a-z0-9_]\\+\\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'

**Comment by Rastusik** [comment] 2016-07-18 23:04
@pivanof nope, I think what you posted is the current version committed in the git repository. I'll try to figure something out tomorrov, but I think it might be a problem to not use the flags

**Comment by pivanof** [comment] 2016-07-18 23:23
No, my version differs from what's committed now in git: I've added backslashes in front of opening and closing parenthesis and in front of `+`. With those changes it works on Linux without `-r` flag.

**Comment by enisoc** [comment] 2016-07-19 02:01
@pivanof I had already added those: https://github.com/youtube/vitess/commit/88d381596d08df6da46eab6ffa93fe178b1bb807

As you said, it works in Linux, but not in OS X.

**Comment by Rastusik** [comment] 2016-07-19 10:55
So, I found out that this pattern works too:

```
sed -e 's,import \([a-z0-9_]*\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'
```

I needed to replace the '+' sign with the '*' sign, which might be problematic in some cases, but it should work in Linux as well as in OSX. The '+' sign seems to be working only with extended regular expressions (the -r parameter in Linux and the -E parameter in OSX)

**Comment by ashudeep-sharma** [comment] 2016-07-19 11:11
Did you miss the -i in the above pattern, this pattern works fine both on linux as well as OSX
`sed **-i** -e 's,import \([a-z0-9_]*\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'`

without -i , i am getting exceptions like these:
_can't load package: /home/ashudeep.sharma/vt/src/github.com/youtube/vitess/go/vt/proto/automationservice/automationservice.pb.go:18:8: local import "." in non-local package
can't load package: /home/ashudeep.sharma/vt/src/github.com/youtube/vitess/go/vt/proto/binlogdata/binlogdata.pb.go:27:8: local import "." in non-local package
can't load package: /home/ashudeep.sharma/vt/src/github.com/youtube/vitess/go/vt/proto/binlogservice/binlogservice.pb.go:18:8: local import "." in non-local package
can't load package: /home/ashudeep.sharma/vt/src/github.com/youtube/vitess/go/vt/proto/query/query.pb.go:48:8: local import "." in non-local package
can't load package: /home/ashudeep.sharma/vt/src/github.com/youtube/vitess/go/vt/proto/queryservice/queryservice.pb.go:18:8: local import "." in non-local package_

**Comment by Rastusik** [comment] 2016-07-19 11:13
oh, yes, sorry, it should be:

```
sed -i -e 's,import \([a-z0-9_]*\) ".",import \1 "github.com/youtube/vitess/go/vt/proto/\1",g'
```

I was testing the pattern outside of the Makefile

**Comment by enisoc** [comment] 2016-07-19 20:29
Thanks! I confirmed it worked on Linux so we'll try it: https://github.com/youtube/vitess/commit/9371dd4c927d3244d0f6c7e6dd89245972840ae4

I'll optimistically mark this fixed. Feel free to reopen if it still doesn't work on OS X.

**Closed by enisoc** 2016-07-19 20:29 UTC
