### ISSUE TITLE
No resources found. etcd-operator installation failed.

### ISSUE THREAD

**Issue by canaanpaul** [youtube/vitess#3602] opened 2018-01-29 06:15 UTC
I installed  kubernetes cluster use kubeadm 1.9.2, I did it as the " Running Vitess on Kubernetes", but get this error:
cd examples/kubernetes/ 
[root@k8s-master kubernetes]# ./etcd-up.sh 
No resources found.
Downloading and installing etcd-operator for first time use...
Cloning into 'etcd-operator'...
remote: Counting objects: 12820, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 12820 (delta 18), reused 32 (delta 12), pack-reused 12757
Receiving objects: 100% (12820/12820), 3.00 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (7689/7689), done.
deployment "etcd-operator" created
No resources found.
etcd-operator installation failed.

**Comment by enisoc** [comment] 2018-01-29 17:58
I think this is the same issue as #3439.

The problem is here:

https://github.com/youtube/vitess/blob/83866b34b70f7767dc28902a08d2228e8d49b1a5/examples/kubernetes/etcd-up.sh#L40-L45

When `kubectl create` returns, there is no guarantee that the `etcdclusters` CRD has been installed. We need to poll with a timeout until the CRD is actually available. Note that checking for the entry in `kubectl get customresourcedefinitions` is also not enough, since the entry will appear there before the CRD is actually ready to be used, which will cause a similar race condition for the subsequent instantiation of `etcd-service-template.yaml` in the script.

Instead, we should poll until `kubectl get etcdclusters.etcd.database.coreos.com` returns a 0 error code. This indicates that the CRD is available for use.

**Comment by sougou** [comment] 2018-02-07 13:03
I'll close this since it's a dup.

**Closed by sougou** 2018-02-07 13:03 UTC
Labels: P3, Status: Duplicate, Type: Question

**Comment by aceinme** [comment] 2018-03-26 09:57
How was it resolved?
