### ISSUE TITLE
flag provided but not defined: -enable_replication_reporter 

### ISSUE THREAD

**Issue by bobymicroby** [youtube/vitess#1709] opened 2016-05-19 13:00 UTC
Hi guys, i am trying the kubernetes tutorial, everything works until ```./vttablet-up.sh .```

This is the log of the pod 
```
kube@master:~/go/src/github.com/youtube/vitess/examples/kubernetes$ kubectl logs vttablet-100 vttablet 

flag provided but not defined: -enable_replication_reporter 
```
I am using the scripts from master and i have tried all published vitess/lite container images for vttablet-pod-template.yaml

**Comment by thompsonja** [comment] 2016-05-19 16:02
Hi Borislav,

Thank you for pointing out this issue!  I believe the problem is that the
flag was added to our kubernetes config files but the docker image has not
yet been updated to include the corresponding change on the vttablet side.
As a workaround you can change the docker image in
vttablet-pod-template.yaml to use vitess/root instead of vitess/lite.  We
will update the docker images accordingly.

Thanks,
Josh

**Comment by enisoc** [comment] 2016-05-19 19:18
This should be fixed now, but note that:

If you have your Kubernetes cluster still running, it might have the vitess/lite image cached. You can force it to re-pull the image by either restarting the Kubernetes cluster, or just changing 'vitess/lite' to 'vitess/lite:latest' before running vttablet-up.sh:

https://github.com/youtube/vitess/blob/master/examples/kubernetes/vttablet-pod-template.yaml#L14

Also please re-pull the latest master branch and refresh the guide page on vitess.io, as I've made some minor fixes to the scripts and docs as well.

**Closed by enisoc** 2016-05-19 19:18 UTC

**Comment by bobymicroby** [comment] 2016-05-20 06:29
Thanks @enisoc . Do you know what will be really helpful, a guide for building the docker images from scratch. I have noticed few times in the issue tracker that inconsistencies between between the pod definitions and the published images.

**Comment by enisoc** [comment] 2016-05-20 22:32
That's a great idea! Here you go:
http://vitess.io/getting-started/docker-build.html :)

**Comment by bobymicroby** [comment] 2016-05-25 07:20
@enisoc Sorry for the late reply, I was offline. Thanks a lot for the docs, they will be of great help :)
